- dns/acceptance.sh
- dns/provider.go
The `dns/acceptance.sh` script starts up a bind server in docker to provide a target to run the acceptance tests against.
This is a couple minor adjustments to that script to make it easier to use:
- Run the local test DNS server on a non-standard port, to avoid conflicts with a real nameserver running on localhost:53
- Clean up the docker containers even if the tests fail, to avoid the need for manual cleanup in that case.
In order to implement this it was necessary to make the update port number configurable in the environment, similar to all of the other settings.
> Make the acctest helper script a little easier to use

- dns/data_dns_txt_record_set_test.go
Looks like the TXT records the test was depending on changed, resulting in [failing tests](https://travis-ci.org/terraform-providers/terraform-provider-dns/builds/291683469#L482)
```
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-dns github.com/terraform-providers/terraform-provider-dns/dns
? github.com/terraform-providers/terraform-provider-dns	[no test files]
--- FAIL: TestAccDataDnsTxtRecordSet_Basic (0.04s)
testing.go:435: Step 0 error: Check failed: Check 1/1 error: Mismatch array count for records: got 4, wanted 3
FAIL
FAIL	github.com/terraform-providers/terraform-provider-dns/dns	0.051s
```
```
$ dig hashicorp.com TXT
[...]
;; QUESTION SECTION:
;hashicorp.com.			IN	TXT
;; ANSWER SECTION:
hashicorp.com.		300	IN	TXT …
```
> Add expected record to fix TestAccDataDnsTxtRecordSet_Basic

- README.md
Trying to build this provider as described in the README currently fails.
> Update Building instructions in the README to reflect new repository location

- dns/resource_dns_a_record_set.go
- dns/resource_dns_a_record_set_test.go
- dns/resource_dns_aaaa_record_set.go
- dns/resource_dns_aaaa_record_set_test.go
This fixes #12 (and also #23). The problem is that the `digitalocean_droplet.ipv6_address` attribute returns an IPv6 address which does not use the `::` substitution, however the `dns_aaaa_record_set` resource when it reads the address back from DNS will get an address that uses the `::` substitution. This means that the addresses will always differ as we're comparing as strings even though the addresses are equivalent and so a `terraform apply` will always contain changes.
This fix works by feeding all IPv6 addresses through `net.ParseIP()` to create an IP object and then turns it back into a string again. The net result is all IPv6 addresses are now formatted consistently (using the `::` substitution as it happens) so the addresses will compare properly using string-based comparison. …
> Compare all IP addresses consistently

- dns/config.go
Use `net.JoinHostPort()` instead of `net.Sprintf()` as it will correctly wrap
an IPv6 address with `[]`'s. Fixes #11.
> Switch to net.JoinHostPort()

- dns/data_dns_txt_record_set_test.go
In the long run we're going to set up a specialized test domain for this so we don't need to keep tweaking for changes to these "real" domains, but this is just a tactical update to get the test passing again.
> Switch the data.dns_txt_record_set test to terraform.io

- dns/resource_dns_a_record_set.go
- dns/resource_dns_a_record_set_test.go
- dns/resource_dns_aaaa_record_set.go
- dns/resource_dns_aaaa_record_set_test.go
- dns/resource_dns_cname_record.go
- dns/resource_dns_cname_record_test.go
- dns/resource_dns_ns_record_set.go
- dns/resource_dns_ns_record_set_test.go
- dns/resource_dns_ptr_record.go
- dns/resource_dns_ptr_record_test.go
This fixes #2.
With tests updated:
```
$ make testacc TEST=./dns TESTARGS='-run=TestAccDns*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./dns -v -run=TestAccDns* -timeout 120m
=== RUN   TestAccDnsARecordSet_Basic
--- FAIL: TestAccDnsARecordSet_Basic (0.05s)
testing.go:434: Step 2 error: Error refreshing: 1 error(s) occurred:
* dns_a_record_set.foo: 1 error(s) occurred:
* dns_a_record_set.foo: dns_a_record_set.foo: Error querying DNS record: 3
=== RUN   TestAccDnsAAAARecordSet_basic
--- FAIL: TestAccDnsAAAARecordSet_basic (0.04s)
testing.go:434: Step 2 error: Error refreshing: 1 error(s) occurred:
* dns_aaaa_record_set.bar: 1 error(s) occurred:
* dns_aaaa_record_set.bar: dns_aaaa_record_set.bar: Error querying DNS record: 3
=== RUN …
```
> Fix NXDOMAIN on read

- dns/data_dns_ptr_record_set.go
- dns/data_dns_ptr_record_set_test.go
- dns/provider.go
- website/dns.erb
- website/docs/d/dns_ptr_record_set.html.markdown
Fix #31 
PTR data source giving users the ability to reverse lookup an ip address to obtain a DNS name. Passing acceptance test using google's public DNS server address (8.8.8.8)
```
=== RUN   TestAccDataDnsPtrRecordSet_Basic
--- PASS: TestAccDataDnsPtrRecordSet_Basic (0.04s)
```
> data/dns_ptr_record_set: Implement data source for PTR

- dns/provider.go
- dns/resource_dns_a_record_set.go
- dns/resource_dns_a_record_set_test.go
- dns/resource_dns_aaaa_record_set.go
- dns/resource_dns_aaaa_record_set_test.go
- dns/resource_dns_cname_record.go
- dns/resource_dns_cname_record_test.go
- dns/resource_dns_ns_record_set.go
- dns/resource_dns_ns_record_set_test.go
- dns/resource_dns_ptr_record.go
- dns/resource_dns_ptr_record_test.go
This should fix #29 and #16 (and obsolete #34).
I've added a common `exchange()` which removes a lot of the DNS query duplication and this also handles the case of UDP truncation by retrying with EDNS0 to set a bigger UDP size and then with TCP if necessary.
I added a simple truncation test case by having an AAAA RR with 14 addresses which is sufficient to exceed the 512 byte limit:
```
$ make testacc TEST=./dns TESTARGS='-run=TestAccDns*'                              
==> Checking that code complies with gofmt requirements...                         
TF_ACC=1 go test ./dns -v -run=TestAccDns* -timeout 120m                           
=== RUN   TestAccDnsARecordSet_Basic                                               
--- PASS: TestAccDnsARecordSet_Basic (0.13s) …
```
> TSIG on reads and handle UDP truncation

- dns/provider.go
Greetings,
a few Get*Val() funcs are defined in dns/provider.go
example for a A record:
```
func getAVal(record interface{}) (string, error) {
recstr := record.(*dns.A).String()
...
```
but no type check is performed before casting
We had an issue where a `dns_a_record_set` was defined but somehow the people managing the DNS zone changed the record to a CNAME record using external tools
The crash log exhibited the exact issue:
```
* dns_a_record_set.test: dns_a_record_set.test: unexpected EOF
panic: interface conversion: interface {} is *dns.CNAME, not *dns.A
2018-03-22T14:39:09.468Z [DEBUG] plugin.terraform-provider-dns_v1.0.0_x4:
2018-03-22T14:39:09.468Z [DEBUG] plugin.terraform-provider-dns_v1.0.0_x4: goroutine 25 [running]:
2018-03-22T14:39:09.468Z [DEBUG] …
```
> checking type on Get*Val(record interface{}) like functions

- dns/config.go
- dns/resource_dns_a_record_set.go
- dns/resource_dns_a_record_set_test.go
- dns/resource_dns_aaaa_record_set.go
- dns/resource_dns_aaaa_record_set_test.go
- dns/resource_dns_cname_record.go
- dns/resource_dns_cname_record_test.go
- dns/resource_dns_ns_record_set.go
- dns/resource_dns_ns_record_set_test.go
- dns/resource_dns_ptr_record.go
- dns/resource_dns_ptr_record_test.go
- dns/validators.go
- dns/validators_test.go
This should fix #24, #19 & #15.
Basically check the TSIG key name is fully-qualified and all lower-case. For resources, validate the zone name is fully qualified and that the record name isn't, due to them being joined with `"%s.%s"` so it should prevent double `".."` which seems to be a common source of misconfiguration.
> Validate TSIG key name and resource zone/record names

- website/docs/d/dns_txt_record_set.html.markdown
I copied the example from the doc and noticed this syntax error.
> Fix hashi_txts output syntax

- dns/provider.go
- dns/provider_test.go
- dns/resource_dns_a_record_set.go
- dns/resource_dns_a_record_set_test.go
- dns/resource_dns_aaaa_record_set.go
- dns/resource_dns_aaaa_record_set_test.go
- dns/resource_dns_cname_record.go
- dns/resource_dns_cname_record_test.go
- dns/resource_dns_ns_record_set.go
- dns/resource_dns_ns_record_set_test.go
- dns/resource_dns_ptr_record.go
- dns/resource_dns_ptr_record_test.go
- dns/validators.go
- dns/validators_test.go
- website/docs/r/dns_a_record_set.html.markdown
- website/docs/r/dns_aaaa_record_set.html.markdown
- website/docs/r/dns_ptr_record.html.markdown
Currently it's not possible to create apex records or naked domains, i.e. `example.com`. This is because both the `name` and `zone` arguments are required on all resources.
This PR updates the `A`, `AAAA`, & `PTR` resources to make the `name` argument optional. `CNAME` is not changed as it's illegal to create one as an apex record. `NS` is also not currently updated because it cannot be deleted properly, (BIND at least will refuse to delete all `SOA` and `NS` apex records from a zone which may create erroring Terraform runs), 
These records can still be imported.
I've done a fair bit of refactoring here to reduce the amount of duplicated code and I've also fixed what is possibly a lurking bug that if you have existing record(s) for the same FQDN and manage a new record, you won't get …
> Allow creating apex records

- dns/provider.go
- dns/resource_dns_txt_record_set.go
- dns/resource_dns_txt_record_set_test.go
- website/dns.erb
- website/docs/r/dns_txt_record_set.html.markdown
This builds on #69 and adds TXT record resource support, a datasource already exists. This restores parity to the resource and datasource types available.
Records can be created with the following:
```hcl
resource "dns_txt_record_set" "google" {
zone = "example.com."
ttl  = 86400
txt = [
"google-site-verification=...",
]
}
```
The only limitation is that a TXT record can technically be comprised of multiple strings and I just concatenate them together into one, however the precedent here is that the golang `net.LookupTXT()` function loses this detail as well. If you create the records with Terraform then you'll be fine.
> TXT record resource

- dns/data_dns_mx_record_set.go
- dns/data_dns_mx_record_set_test.go
- dns/provider.go
- dns/resource_dns_mx_record_set.go
- dns/resource_dns_mx_record_set_test.go
- website/dns.erb
- website/docs/d/dns_mx_record_set.html.markdown
- website/docs/r/dns_mx_record_set.html.markdown
The builds on #69 and adds MX record support.
Records can be created with the following:
```hcl
resource "dns_mx_record_set" "mx" {
zone = "example.com."
ttl  = 86400
mx {
preference = 10
exchange   = "smtp.example.com."
}
depends_on = [
"dns_a_record_set.smtp",
"dns_aaaa_record_set.smtp",
]
}
```
**EDIT:** I've found that if you try and set the MX pointing to a record that doesn't exist in the zone, BIND will refuse to add it so you need to create an A or AAAA record set and add `depends_on = [ ... ]` to the MX record resource to ensure they're created first. I've updated the documentation with an example of this.
Records can be queried with:
```hcl
data "dns_mx_record_set" "mail" {
domain = "example.com."
}
output "mail" {
value = "${data.dns_mx_record_set.mail.mx.0.exchange}"
}
``` …
> MX record resource and datasource

- dns/data_dns_a_record_set_test.go
- dns/data_dns_aaaa_record_set_test.go
- dns/data_dns_cname_record_set_test.go
- dns/data_dns_mx_record_set_test.go
- dns/data_dns_ns_record_set_test.go
- dns/data_dns_ptr_record_set_test.go
- dns/data_dns_srv_record_set.go
- dns/data_dns_srv_record_set_test.go
- dns/provider.go
- dns/resource_dns_srv_record_set.go
- dns/resource_dns_srv_record_set_test.go
- website/dns.erb
- website/docs/d/dns_srv_record_set.html.markdown
- website/docs/r/dns_srv_record_set.html.markdown
This builds on #69 and adds SRV record support.
Records can be created with the following:
```hcl
resource "dns_srv_record_set" "sip" {
zone = "example.com."
name = "_sip._tcp"
ttl  = 86400
srv {
priority = 10
weight   = 60
target   = "sip.example.com."
port     = 5060
}
}
```
Records can be queried with:
```hcl
data "dns_srv_record_set" "kerberos" {
service = "_kerberos._tcp.example.com."
}
output "kerberos" {
value = "${data.dns_srv_record_set.kerberos.srv.0.target}"
}
```
The only problem I have with the data source is that I don't know of a reliable external SRV record I can query for tests, so they're currently commented out.
Fixes #45
> SRV record resource and datasource

- dns/data_dns_txt_record_set_test.go
The test for `data_dns_txt_record_set_test` includes a check of the TXT records for the real-world terraform.io domain. Previously, there were three google-site-verification entries for terraform.io that are included in the test. However, a new entry for keybase-site-verification appears to have been added to terraform.io that is now causing this test to fail. 
This PR adds the missing TXT entry. 
It might be a good idea to create some permanent DNS entries intended for testing this functionality (perhaps in a subdomain of terraform.io?) so that it does not break again in the future.
> add missing TXT entry for terraform.io in data_dns_txt_record_set_test

- internal/provider/provider.go
TSIG entries were erroneously added multiple times during retries. This PR addresses the problem.
> Move retries to after adding TSIG to prevent multiple entries from being added during retries

- website/docs/index.html.markdown
When viewing the page, it can be helpful to be linked directly to the IETF RFC pages.
> docs/provider: Clarify and linkify provider summary

- .github/dependabot.yml
So it will trigger a Terraform Plugin SDK upgrade pull request. 😉
> deps: Enable dependabot configuration for Go Modules and GitHub Actions

- internal/provider/provider.go
Data sources would require conversion to the `github.com/miekg/dns` Go package, which can potentially be handled later.
Example debug log output:
```
2021/06/02 16:17:43 [DEBUG] Sending DNS message to server (ns.example.com:15353):
;; opcode: UPDATE, status: NOERROR, id: 42066
;; flags:; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 1
;; QUESTION SECTION:
;example.com.	IN	 SOA
;; AUTHORITY SECTION:
foo.example.com.	300	IN	TXT	"bar"
foo.example.com.	300	IN	TXT	"foo"
;; ADDITIONAL SECTION:
;; TSIG PSEUDOSECTION:
; 691515462.sig-ns.example.com.	0	CLASS255	TSIG	 gss-tsig. 20210602201743 300 0  42066 0 0
2021/06/02 16:17:43 [DEBUG] Receiving DNS message from server (ns.example.com:15353):
;; opcode: UPDATE, status: NOERROR, id: 42066
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, …
```
> provider: Add debug logging for resource DNS messages

- go.mod
- go.sum
No other dependency updates available for direct go.mod dependencies.
> Update dns and krb5 dependencies

- internal/provider/data_dns_a_record_set_test.go
- internal/provider/data_dns_aaaa_record_set_test.go
- internal/provider/data_dns_cname_record_set_test.go
- internal/provider/data_dns_mx_record_set_test.go
- internal/provider/data_dns_ns_record_set_test.go
- internal/provider/data_dns_srv_record_set_test.go
- internal/provider/data_dns_txt_record_set_test.go
Reference: https://github.com/hashicorp/tf-eco-acctest-infrastructure/issues/61
Closes #112
Reference: https://github.com/hashicorp/terraform-provider-dns/pull/144
Closes #154
Reference: https://github.com/hashicorp/terraform-provider-dns/issues/157
> tests: Switch to hashicorptest.com DNS records for testing

- README.md
- internal/provider/acceptance.sh
- internal/provider/testdata/krb5.conf
Closes #140
Closes #143
Updates DNS and Kerberos port numbers to not collide with mac OS managed processes. Also, adds README documentation (and quick acceptance test script checks) for prerequisites.
Output from acceptance testing on mac OS 11.4:
```console
$ ./internal/provider/acceptance.sh
+ command -v docker
+ command -v go
+ command -v kinit
+ command -v make
+ command -v terraform
+ grep -q ns.example.com /etc/hosts
+ docker buildx build --target kdc --tag kdc internal/provider/testdata/
[+] Building 0.8s (20/20) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                          0.0s
=> => transferring dockerfile: 32B …
```
> tests/provider: Support macOS in acceptance testing and document prerequisites

- .github/workflows/test.yml
- internal/provider/acceptance.sh
- internal/provider/testdata/Dockerfile
closes #256 
> For reference, prior to this PR:
> - last successful run of tests: https://github.com/hashicorp/terraform-provider-dns/actions/runs/3468260802
> - first failed run of tests: https://github.com/hashicorp/terraform-provider-dns/actions/runs/3692207675
The provider acceptance tests started failing after `ubuntu-latest` was switched from `20.04` to `22.04`: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221204.2
The acceptance tests run by [starting up](https://github.com/hashicorp/terraform-provider-dns/blob/main/internal/provider/acceptance.sh) a BIND DNS container, along with two sidecar containers that facilitate Kerberos functionality. Two of these containers run their processes using `systemd` inside a Centos 7 image, as seen in the …
> ci: update acceptance tests to allow running on newer docker versions 

- .changes/unreleased/BUG FIXES-20230419-160433.yaml
- .changes/unreleased/BUG FIXES-20230419-161012.yaml
- internal/provider/config.go
- internal/provider/provider.go
- internal/provider/provider_framework.go
- internal/provider/provider_test.go
Fixes: #289
Fixes: #290 
The migration to `terraform-plugin-framework` in `v3.3.0` introduced a panic from not correctly handling the errors returned from `config.client()` which causes the `exchange()` to panic when trying to access a `*DNSClient` which is set to `nil`. This PR handles and returns the error to the user, preventing the panic. An additional test `TestAccProvider_InvalidClientConfig()` has been added to test this scenario.
It also introduced a bug where the `DNSClient` was not being configured with the user's Terraform configuration and only using the set environment variables. This PR correctly sets the `DNSClient` using the config values and uses environment variables to set a variable only if the variable isn't already set in the user Terraform configuration.
> Correctly handle DNS client configuration

- .changes/unreleased/BUG FIXES-20230421-143032.yaml
- docs/index.md
- internal/provider/provider.go
- internal/provider/provider_framework.go
- internal/provider/provider_test.go
Closes #293
Using terraform-plugin-mux requires the provider schemas of all underlying provider implementations to exactly match to prevent confusing behavior. One legacy quirk of terraform-plugin-sdk was that it allows an attribute to be marked in a schema as required, but also support optional configuration via a default. This confusing definition of configuration requirement is no longer supported in terraform-plugin-framework.
This changeset includes the following:
- Adjusts the provider acceptance testing to always use mux server (except for the two remaining sdk resources), similar to the production binary.
- Adjusts the provider schema definitions to always use optional when the configuration value may be sourced from environment variable.
- Adjusts the provider schema descriptions …
> provider: Test using mux server, prevent mux server errors, and add provider environment variables to descriptions

- internal/provider/provider_framework.go
- internal/provider/provider_framework_test.go
Reference: https://github.com/hashicorp/terraform-provider-dns/issues/290
Introduce unit testing for the complex `(dnsProvider).Configure()` method. This initial testing covers no configuration/environment variables and the `update` list block `port`, `server`, and `transport` attributes (along with their associated environment variables).
> internal/provider: Initial unit testing for provider Configure method

- internal/provider/provider_test.go
- internal/provider/resource_dns_a_record_set_test.go
- internal/provider/resource_dns_aaaa_record_set_test.go
- internal/provider/resource_dns_cname_record_test.go
- internal/provider/resource_dns_mx_record_set_test.go
- internal/provider/resource_dns_ns_record_set_test.go
- internal/provider/resource_dns_ptr_record_test.go
- internal/provider/resource_dns_srv_record_set_test.go
- internal/provider/resource_dns_txt_record_set_test.go
These functions all perform the same logic, just with differing record types and names.
> internal/provider: Consolidate testing record removal logic

- .changes/unreleased/BUG FIXES-20230501-131218.yaml
- internal/provider/provider_framework.go
- internal/provider/provider_framework_test.go
- internal/provider/provider_test.go
Closes #298
Previously:
```
--- FAIL: TestDnsProviderConfigure (0.00s)
--- FAIL: TestDnsProviderConfigure/update-timeout-config-number (0.00s)
/Users/bflad/src/github.com/hashicorp/terraform-provider-dns/internal/provider/provider_framework_test.go:580: unexpected difference:   &provider.ConfigureResponse{
  	DataSourceData: nil,
- 	Diagnostics: diag.Diagnostics{
- 		diag.ErrorDiagnostic{
- 			detail:  `Timeout cannot be parsed as an integer: strconv.Atoi: parsing "\`...,
- 			summary: "Invalid DNS Provider timeout Value",
- 		},
- 	},
+ 	Diagnostics:  nil,
- 	ResourceData: nil,
+ 	ResourceData: &provider.DNSClient{
+ 		c:         &dns.Client{Net: "udp", Timeout: s"5s"},
+ 		srv_addr:  ":53",
+ 		transport: "udp",
+ 		retries:   3,
+ 	},
  }
--- FAIL: …
```
> provider: Ensure timeout configuration value is parsed correctly

- internal/provider/provider_test.go
- internal/provider/resource_dns_a_record_set_test.go
- internal/provider/resource_dns_aaaa_record_set_test.go
Clearing out some queued code changes locally.
For consistency with the rest of the provider acceptance testing, the lingering terraform-plugin-sdk based resources can use the same testing setup as the terraform-plugin-framework based resources (which themselves all use the muxed provider for testing).
> internal/provider: Migrate rest of acceptance testing from ProviderFactories to ProtoV5ProviderFactories

- .changes/unreleased/BUG FIXES-20230908-135841.yaml
- .changes/unreleased/BUG FIXES-20230908-135858.yaml
- .changes/unreleased/ENHANCEMENTS-20230908-135801.yaml
- .changes/unreleased/NOTES-20230908-100319.yaml
- README.md
- go.mod
- tools/go.mod
> all: Update Go Module to Go 1.20

- .changes/unreleased/NOTES-20240910-073157.yaml
- README.md
- go.mod
- tools/go.mod
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.7
> all: Bump minimum Go module version to 1.22

- .changes/3.4.3.md
- CHANGELOG.md
Prepares changelog for a `3.4.3` release with the new CRT migration process. The `version/VERSION` file was already set to that version via #545 (and #546)
> Prepare for 3.4.3 release
